BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS `Questions` (
    `QuestionID`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `QuestionText`  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `Response` (
    `ResponseID`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `PatientID` INTEGER NOT NULL,
    FOREIGN KEY(`PatientID`) REFERENCES `Patient`(`PatientID`),
    `OptionID`  INTEGER NOT NULL,
    FOREIGN KEY(`OptionID`) REFERENCES `Options`(`OptionID`),
    `QuestionID`    INTEGER NOT NULL,
    FOREIGN KEY(`QuestionID`) REFERENCES `Questions`(`QuestionID`),
    `Score` INTEGER,
    FOREIGN KEY(`Score`) REFERENCES `Options`(`Score`),
    `Question3Input` TEXT
);

CREATE TABLE IF NOT EXISTS `Patient` (
    `PatientID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `name`   TEXT NOT NULL,
    `gender`    TEXT NOT NULL,
    `age`   INTEGER NOT NULL,
    `email` TEXT NOT NULL,
    `password`  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `Options` (
    `QuestionID`    INTEGER NOT NULL,
    FOREIGN KEY(`QuestionID`) REFERENCES `Questions`(`QuestionID`),
    `OptionID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `OptionText`    TEXT NOT NULL,
    `Score` INTEGER,
    `QuestionType` TEXT NOT NULL
);

INSERT INTO `Questions` (QuestionID, QuestionText)
VALUES (1, 'Do you know what caused your current back pain?'),
       (2, 'If yes, choose an option from the list below:'),
       (3, 'What do you think is wrong with your back?'),
       (4, 'If you have been treated for back pain, were you satisfied with your treatment?'),
       (5, 'What medication do you take to manage your back pain? Please tick all options that apply'),
       (6, 'How effective is the medication in reducing your back pain?'),
       (7, 'Where is your pain? Please tick all body areas that apply'),
       (8, 'Is your pain there all the time?'),
       (9, 'What type of pain is it? Please tick all options that apply'),
       (10, 'When is your pain at its worst?'),
       (11, 'Can you ease your back pain?'),
       (12, 'How do you ease your back pain? Please tick all options that apply'),
       (13, 'In general, is your back pain getting better, staying the same or getting worse?'),
       (14, 'From the list below, please tick all the activities that make your pain worse.'),
       (15, 'From the list below, please tick all the activities that stop or decrease your pain.'),
       (16, 'Is this the first time you have experienced this type of pain?'),
       (17, 'If you had a previous episode of back pain, what helped in making your pain better? Please tick all options that apply'),
       (18, 'Other than your back pain, do you experience other odd sensations in your back or legs (for example: crawling sensation, stinging, pressure)'),
       (19, 'Please tick all the areas where you experience this feeling:'),
       (20, 'On average, how many hours do you sleep?'),
       (21, 'Does your back pain wake you up every night?'),
       (22, 'If you wake up with back pain, can you get back to sleep?'),
       (23, 'How strongly do you agree with this statement: ''I believe that my job caused /contributed to my back pain'''),
       (24, 'Do you feel supported by your boss and/or co-workers?'),
       (25, 'How is your back pain affecting your work?'),
       (26, 'Are you off work right now because of your back pain?'),
       (27, 'How long have you been off work?'),
       (28, 'How likely it is that you would return to work within six months?'),
       (29, '''I can''t do my normal daily activities because of my back pain'''),
       (30, '''My back pain is negatively affecting my social life'''),
       (31, '''My back pain is affecting my relationship with my significant other'''),
       (32, '''I don''t know what makes my back pain worse or what eases it'''),
       (33, '''My back pain makes me feel stressed/anxious'''),
       (34, '''Stress increases my back pain'''),
       (35, '''Physical activity increases my back pain'''),
       (36, '''Since my back pain started, I feel more tired'''),
       (37, '''I have lost interest and/or pleasure in doing things because of my back pain'''),
       (38, '''I don''t think my family and friends understand what I''m going through with my back pain'''),
       (39, '''I don''t think my back pain will ever go away''');

INSERT INTO `Options` (QuestionID, OptionID, OptionText, Score, QuestionType)
VALUES (1,1,'Yes',0,'Radiobox'),
       (1,2,'No',2,'Radiobox'),
       (1,3,'Not sure',1,'Radiobox'),
       (2,4,'Car accident',1,'Radiobox'),
       (2,5,'Sport injury',0,'Radiobox'),
       (2,6,'Lifting/bending accident',0,'Radiobox'),
       (2,7,'Falling down',0,'Radiobox'),
       (2,8,'Other trauma',0,'Radiobox'),
       (2,9,'Work related',1,'Radiobox'),
       (2,10,'Other',0,'Radiobox'),
       (2,11,'Nothing specific',1,'Radiobox'),
       (3,12,'Write here...',0,'Textbox'),
       (4,13,'Yes, I was satisfied with the treatment',NULL,'Radiobox'),
       (4,14,'I was neither satisfied nor dissatisfied with the treatment',1,'Radiobox'),
       (4,15,'No, I was not satisfied with the treatment',2,'Radiobox'),
       (4,16,'I was never treated for back pain',NULL,'Radiobox'),
       (5,17,'Paracetamol',1,'Tickbox'),
       (5,18,'Ibuprofen',1,'Tickbox'),
       (5,19,'Codeine',1,'Tickbox'),
       (5,20,'Diazepam',1,'Tickbox'),
       (5,21,'Amitriptyline',1,'Tickbox'),
       (5,22,'Duloxetine/Cymbalta',1,'Tickbox'),
       (5,23,'Gabapentin',1,'Tickbox'),
       (5,24,'Tramadol',1,'Tickbox'),
       (5,25,'Hydrocodone',1,'Tickbox'),
       (5,26,'Cortisone',1,'Tickbox'),
       (5,27,'Acetaminophen',1,'Tickbox'),
       (5,28,'Glucosamine',1,'Tickbox'),
       (5,29,'Valium',1,'Tickbox'),
       (5,30,'Naproxen',1,'Tickbox'),
       (5,31,'Other',1,'Tickbox'),
       (5,32,'I don''t take any medication for my back pain',0,'Tickbox'),
       (6,33,'Effective',0,'Radiobox'),
       (6,34,'Not sure',1,'Radiobox'),
       (6,35,'Ineffective',2,'Radiobox'),
       (7,36,'Neck',1,'Tickbox'),
       (7,37,'Right shoulder',1,'Tickbox'),
       (7,38,'Left shoulder',1,'Tickbox'),
       (7,39,'Right arm',1,'Tickbox'),
       (7,40,'Left arm',1,'Tickbox'),
       (7,41,'Upper back',1,'Tickbox'),
       (7,42,'Lower back',1,'Tickbox'),
       (7,43,'Right buttock',1,'Tickbox'),
       (7,44,'Left buttock',1,'Tickbox'),
       (7,45,'Right hip',1,'Tickbox'),
       (7,46,'Left hip',1,'Tickbox'),
       (7,47,'Right leg',1,'Tickbox'),
       (7,48,'Left leg',1,'Tickbox'),
       (7,49,'Slider',NULL,'Slider'),
       (7,50,'BodyDisplay',NULL,'BodyDisplay'),
       (8,51,'My pain is there all the time',2,'Radiobox'),
       (8,52,'My pain comes and goes',0,'Radiobox'),
       (8,53,'Not sure',1,'Radiobox'),
       (9,54,'Deep',1,'Tickbox'),
       (9,55,'Nagging',1,'Tickbox'),
       (9,56,'Dull',1,'Tickbox'),
       (9,57,'Sharp',1,'Tickbox'),
       (9,58,'Shooting',1,'Tickbox'),
       (9,59,'Dull ache',1,'Tickbox'),
       (9,60,'Like lighting',1,'Tickbox'),
       (9,61,'Burning',1,'Tickbox'),
       (9,62,'Pressure',1,'Tickbox'),
       (9,63,'Stinging',1,'Tickbox'),
       (9,64,'Aching',1,'Tickbox'),
       (9,65,'Throbbing',1,'Tickbox'),
       (9,66,'Spread over a wide area',2,'Tickbox'),
       (10,67,'In the morning',1,'Radiobox'),
       (10,68,'At the end of the day',1,'Radiobox'),
       (10,69,'My pain is there all day long',2,'Radiobox'),
       (11,70,'Yes',0,'Radiobox'),
       (11,71,'Sometimes',1,'Radiobox'),
       (11,72,'No',2,'Radiobox'),
       (12,73,'Medication/pain killers',0,'Tickbox'),
       (12,74,'Rest',0,'Tickbox'),
       (12,75,'Walking',0,'Tickbox'),
       (12,76,'Standing',0,'Tickbox'),
       (12,77,'Sitting',0,'Tickbox'),
       (12,78,'Exercise',0,'Tickbox'),
       (12,79,'Massage',0,'Tickbox'),
       (12,80,'Hot pack',0,'Tickbox'),
       (12,81,'Cold pack',0,'Tickbox'),
       (12,82,'Other',0,'Tickbox'),
       (12,83,'I am unable to ease my back pain',2,'Tickbox'),
       (13,84,'My pain is getting better',0,'Radiobox'),
       (13,85,'My pain has stayed the same',1,'Radiobox'),
       (13,86,'My pain is getting worse',2,'Radiobox'),
       (14,87,'Sitting relaxed',0,'Tickbox'),
       (14,88,'Sitting up straight',0,'Tickbox'),
       (14,89,'Standing',0,'Tickbox'),
       (14,90,'Walking',0,'Tickbox'),
       (14,91,'Lifting',0,'Tickbox'),
       (14,92,'Forward bending',0,'Tickbox'),
       (14,93,'Any activity that I do for a long period of time increases my back pain',1,'Tickbox'),
       (14,94,'Everything I do causes me pain',2,'Tickbox'),
       (15,95,'Walking',0,'Tickbox'),
       (15,96,'Changing positions',0,'Tickbox'),
       (15,97,'Sitting down',0,'Tickbox'),
       (15,98,'Avoiding activities that causes me pain ',2,'Tickbox'),
       (15,99,'Stretching my back',0,'Tickbox'),
       (15,100,'Moving about',0,'Tickbox'),
       (15,101,'Painkillers',1,'Tickbox'),
       (15,102,'Nothing I do stops my pain',2,'Tickbox'),
       (16,103,'Yes',0,'Radiobox'),
       (16,104,'No',2,'Radiobox'),
       (16,105,'Not sure',1,'Radiobox'),
       (17,106,'Medication/painkillers/injejctoins',1,'Tickbox'),
       (17,107,'Rest',1,'Tickbox'),
       (17,108,'Exercise',0,'Tickbox'),
       (17,109,'Massage/physiotherapy/chiropractic/osteopathy',1,'Tickbox'),
       (17,110,'Nothing helped',2,'Tickbox'),
       (18,111,'Yes',2,'Radiobox'),
       (18,112,'No',0,'Radiobox'),
       (18,113,'I don''t know',1,'Radiobox'),
       (19,114,'Neck',1,'Tickbox'),
       (19,115,'Right shoulder',1,'Tickbox'),
       (19,116,'Left shoulder',1,'Tickbox'),
       (19,117,'Right arm',1,'Tickbox'),
       (19,118,'Left arm',1,'Tickbox'),
       (19,119,'Upper back',1,'Tickbox'),
       (19,120,'Lower back',1,'Tickbox'),
       (19,121,'Right buttock',1,'Tickbox'),
       (19,122,'Left buttock',1,'Tickbox'),
       (19,123,'Right hip',1,'Tickbox'),
       (19,124,'Left hip',1,'Tickbox'),
       (19,125,'Right leg',1,'Tickbox'),
       (19,126,'Left leg',1,'Tickbox'),
       (19,127,'BodyDisplay',NULL,'BodyDisplay'),
       (20,128,'Slider',NULL, 'Slider'),
       (21,129,'Yes',2,'Radiobox'),
       (21,130,'No',0,'Radiobox'),
       (22,131,'Yes',0,'Radiobox'),
       (22,132,'Sometimes',1,'Radiobox'),
       (22,133,'No',2,'Radiobox'),
       (23,134,'Agree',2,'Radiobox'),
       (23,135,'Neither agree nor disagree',1,'Radiobox'),
       (23,136,'Disagree',0,'Radiobox'),
       (23,137,'I don''t work',NULL,'Radiobox'),
       (24,138,'Yes',0,'Radiobox'),
       (24,139,'No',2,'Radiobox'),
       (24,140,'I don''t know',1,'Radiobox'),
       (24,141,'Not applicable',NULL,'Radiobox'),
       (25,142,'Not at all',0,'Radiobox'),
       (25,143,'Sometimes',0,'Radiobox'),
       (25,144,'Frequently',1,'Radiobox'),
       (25,145,'I am unable to work because of my back pain',2,'Radiobox'),
       (26,146,'Yes',2,'Radiobox'),
       (26,147,'No',0,'Radiobox'),
       (26,148,'I don''t work',0,'Radiobox'),
       (27,149,'Less than 3 months',0,'Radiobox'),
       (27,150,'Between 1 to 6 months',1,'Radiobox'),
       (27,151,'More than 6 months',2,'Radiobox'),
       (28,152,'Likely',0,'Radiobox'),
       (28,153,'Not sure',1,'Radiobox'),
       (28,154,'Unlikely',2,'Radiobox'),
       (29,155,'Agree',2,'Radiobox'),
       (29,156,'Neither agree nor disagree',1,'Radiobox'),
       (29,157,'Disagree',0,'Radiobox'),
       (30,158,'Agree',2,'Radiobox'),
       (30,159,'Neither agree nor disagree',1,'Radiobox'),
       (30,160,'Disagree',0,'Radiobox'),
       (31,161,'Agree',2,'Radiobox'),
       (31,162,'Neither agree nRadioboxor disagree',1,'Radiobox'),
       (31,163,'Disagree',0,'Radiobox'),
       (32,164,'Agree',2,'Radiobox'),
       (32,165,'Neither agree nor disagree',1,'Radiobox'),
       (32,166,'Disagree',0,'Radiobox'),
       (33,167,'Agree',2,'Radiobox'),
       (33,168,'Neither agree nor disagree',1,'Radiobox'),
       (33,169,'Disagree',0,'Radiobox'),
       (34,170,'Agree',2,'Radiobox'),
       (34,171,'Neither agree nor disagree',1,'Radiobox'),
       (34,172,'Disagree',0,'Radiobox'),
       (35,173,'Agree',2,'Radiobox'),
       (35,174,'Neither agree nor disagree',1,'Radiobox'),
       (35,175,'Disagree',0,'Radiobox'),
       (36,176,'Agree',2,'Radiobox'),
       (36,177,'Neither agree nor disagree',1,'Radiobox'),
       (36,178,'Disagree',0,'Radiobox'),
       (37,179,'Agree',2,'Radiobox'),
       (37,180,'Neither agree nor disagree',1,'Radiobox'),
       (37,181,'Disagree',0,'Radiobox'),
       (38,182,'Agree',2,'Radiobox'),
       (38,183,'Neither agree nor disagree',1,'Radiobox'),
       (38,184,'Disagree',0,'Radiobox'),
       (39,185,'Agree',2,'Radiobox'),
       (39,186,'Neither agree nor disagree',1,'Radiobox'),
       (39,187,'Disagree',0,'Radiobox');

COMMIT;
