BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Response` (
	`ResponseID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`OptionID`	INTEGER NOT NULL UNIQUE,
	`QuestionID`	INTEGER NOT NULL UNIQUE,
	`PatientID`	INTEGER NOT NULL UNIQUE
);
COMMIT;
